#!/usr/bin/env bash

# Copyright (c) 2021-2026 community-scripts ORG
# Author: nano-rs
# License: MIT | https://github.com/community-scripts/ProxmoxVE/raw/main/LICENSE
# Source: https://github.com/nano-rs/nano

# This runs INSIDE the freshly created LXC. The function library (color, msg_*,
# update_os, $STD, motd_ssh, customize, ...) is injected by the ProxmoxVE
# build.func via $FUNCTIONS_FILE_PATH — same contract every install/ file uses.
source /dev/stdin <<<"$FUNCTIONS_FILE_PATH"
color
verb_ip6
catch_errors
setting_up_container
network_check
update_os

# nano open-core source. The compose + ClickHouse/Vector/nginx configs are
# pulled straight from the upstream project repo (nano-rs/nano), exactly like
# nano's own install.sh — no third-party bundle. Override NANO_BRANCH to test an
# unmerged branch.
NANO_BRANCH="${NANO_BRANCH:-main}"
DEPLOY_DIR="/opt/nano"

msg_info "Installing Dependencies"
$STD apt-get install -y \
  curl \
  ca-certificates \
  gnupg \
  openssl
# yq: used below to apply the two unprivileged-LXC compose adaptations. Install
# into /usr/bin so it's on PATH in the install context.
curl -fsSL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/bin/yq
chmod +x /usr/bin/yq
msg_ok "Installed Dependencies"

msg_info "Installing Docker"
DOCKER_CONFIG_PATH='/etc/docker/daemon.json'
mkdir -p "$(dirname "$DOCKER_CONFIG_PATH")"
# journald log driver keeps the LXC disk from filling with json-file logs.
echo -e '{\n  "log-driver": "journald"\n}' >"$DOCKER_CONFIG_PATH"
$STD sh <(curl -fsSL https://get.docker.com)
msg_ok "Installed Docker"

msg_info "Fetching nano (open-core) from nano-rs/nano"
mkdir -p "$DEPLOY_DIR"
# Pull only what the compose mounts: the opensource compose, the digest
# lockfile, and the ClickHouse / Vector / nginx config trees.
curl -fsSL "https://github.com/nano-rs/nano/archive/refs/heads/${NANO_BRANCH}.tar.gz" |
  tar -xz -C "$DEPLOY_DIR" --strip-components=1 \
    "nano-${NANO_BRANCH}/docker-compose.opensource.yml" \
    "nano-${NANO_BRANCH}/images.lock" \
    "nano-${NANO_BRANCH}/config/vector" \
    "nano-${NANO_BRANCH}/config/nginx/nginx.opensource.conf" \
    "nano-${NANO_BRANCH}/clickhouse/config.d" \
    "nano-${NANO_BRANCH}/clickhouse/users.d"
# Make it the default compose file so `docker compose ...` (here and in the
# ct/ update flow) needs no -f.
mv "${DEPLOY_DIR}/docker-compose.opensource.yml" "${DEPLOY_DIR}/docker-compose.yml"
msg_ok "Fetched nano"

msg_info "Adapting compose for unprivileged LXC"
cd "$DEPLOY_DIR" || exit 1
# 1) Dragonfly ships `ulimits: memlock: -1`. Setting RLIMIT_MEMLOCK to unlimited
#    is not permitted in an unprivileged LXC (Docker can't exceed the container's
#    memlock hard cap) -> "error setting rlimit type 8: operation not permitted",
#    and the container never starts. Dragonfly runs fine without it at this
#    maxmemory cap (the ulimit only mattered for io_uring on pre-5.12 kernels).
yq -i 'del(.services.dragonfly.ulimits)' docker-compose.yml
# 2) Dragonfly's default registry (docker.dragonflydb.io) intermittently times
#    out; the GHCR mirror resolves reliably (NAN-1217).
yq -i '.services.dragonfly.image = "ghcr.io/dragonflydb/dragonfly:latest"' docker-compose.yml
# Fail loudly if either patch didn't take — a silently-unpatched compose would
# crash-loop dragonfly (memlock) and take the stack down.
if grep -q 'memlock' docker-compose.yml || grep -q 'docker.dragonflydb.io' docker-compose.yml; then
  msg_error "Failed to adapt compose for unprivileged LXC (dragonfly patch did not apply)"
  exit 1
fi
msg_ok "Adapted compose"

msg_info "Generating secrets and environment"
# Generated once and persisted to ${DEPLOY_DIR}/.env on the container disk so a
# stack restart reuses the SAME keys. Rotating them would orphan secret-at-rest
# data (NANOSIEM_ENCRYPTION_KEY) and log everyone out (JWT_SECRET). Mirrors the
# key set in upstream .env.opensource.example.
LOCAL_IP="$(hostname -I | awk '{print $1}')"
cat <<EOF >"${DEPLOY_DIR}/.env"
# nano SIEM environment — generated by nano-proxmox install on first boot.
# Consumed by docker-compose.yml (\${...} interpolation). Keep this file.

# Image tag pulled from ghcr.io/nano-rs/* (digest-pinned in images.lock).
NANO_VERSION=latest

# Public URL analysts hit (nginx reverse proxy). Drives CORS + cookie scope.
BASE_URL=http://${LOCAL_IP}

# Plain-HTTP appliance -> dev mode so the auth refresh cookie is set without the
# Secure flag (browsers drop Secure cookies over http://). Front with HTTPS and
# set this to false for production exposure.
NANOSIEM_DEV_MODE=true

# --- Secrets (32-byte hex) ---
POSTGRES_PASSWORD=$(openssl rand -hex 32)
CLICKHOUSE_PASSWORD=$(openssl rand -hex 32)
CLICKHOUSE_ADMIN_PASSWORD=$(openssl rand -hex 32)
JWT_SECRET=$(openssl rand -hex 32)
NANOSIEM_ENCRYPTION_KEY=$(openssl rand -hex 32)

# --- Log ingestion ---
# Clients ship logs with: Authorization: Bearer \${VECTOR_AUTH_TOKEN}
VECTOR_AUTH_TOKEN=$(openssl rand -hex 24)

RUST_LOG=info
EOF
chmod 600 "${DEPLOY_DIR}/.env"
msg_ok "Generated secrets and environment"

msg_info "Pulling nano images (first run downloads ~12 images — be patient)"
# Serialize the pull: a fully-parallel pull fires dozens of simultaneous CDN
# lookups and can overwhelm a small resolver; retry to ride out hiccups
# (NAN-1224 / NAN-1230).
export COMPOSE_PARALLEL_LIMIT=1
pull_ok=0
for _ in 1 2 3 4 5; do
  if $STD docker compose pull; then
    pull_ok=1
    break
  fi
  sleep 15
done
if [[ "$pull_ok" -ne 1 ]]; then
  msg_error "Failed to pull images after 5 attempts (check network/DNS)"
  exit 1
fi
msg_ok "Pulled images"

# Supply-chain check: confirm the first-party images we just pulled match the
# CI-vouched manifest digests in images.lock. Docker already checksum-verifies
# layers, but that doesn't prove the tag wasn't re-pushed. Non-fatal: images.lock
# tracks the latest release, so a freshly-pushed :latest can briefly differ.
msg_info "Verifying nano image digests against images.lock"
digest_mismatch=0
while read -r repo expected; do
  [[ -z "$repo" || "$repo" == \#* ]] && continue
  actual="$(docker image inspect "${repo}:latest" \
    --format '{{range .RepoDigests}}{{println .}}{{end}}' 2>/dev/null |
    grep -F "${repo}@" | head -1)"
  actual="${actual##*@}"
  [[ "$actual" != "$expected" ]] && digest_mismatch=1
done <images.lock
if [[ "$digest_mismatch" -eq 0 ]]; then
  msg_ok "Image digests verified"
else
  msg_warn "Image digest(s) differ from images.lock — continuing (lockfile tracks the latest release)"
fi

msg_info "Starting nano SIEM stack"
$STD docker compose up -d --remove-orphans
msg_ok "Started nano SIEM stack"

msg_info "Waiting for nano API (first boot runs ClickHouse migrations)"
health_ok=0
for _ in $(seq 1 60); do
  if curl -fsS "http://127.0.0.1:80/api/health" >/dev/null 2>&1; then
    health_ok=1
    break
  fi
  sleep 5
done
if [[ "$health_ok" -eq 1 ]]; then
  msg_ok "nano API is healthy"
else
  msg_error "nano API did not become healthy within 5 minutes — check 'docker compose logs' in ${DEPLOY_DIR}"
fi

# Surface the ingest token (also in ${DEPLOY_DIR}/.env) for log-shipper setup.
VECTOR_AUTH_TOKEN="$(awk -F= '/^VECTOR_AUTH_TOKEN=/{print $2}' "${DEPLOY_DIR}/.env")"
{
  echo "nano SIEM ingest token (Authorization: Bearer <token>):"
  echo "  ${VECTOR_AUTH_TOKEN}"
} >~/nano.creds

motd_ssh
customize

msg_info "Cleaning up"
$STD apt-get -y autoremove
$STD apt-get -y autoclean
msg_ok "Cleaned"
