#!/usr/bin/env bash

# Copyright (c) 2024-2026 nano-rs
# Author: nano-rs (https://nano.rs)
# License: Apache-2.0
# Source: https://github.com/nano-rs/nano-proxmox

# This runs INSIDE the freshly created LXC. The function library (color, msg_*,
# update_os, $STD, motd_ssh, customize, ...) is injected by the ProxmoxVE
# build.func via $FUNCTIONS_FILE_PATH — same contract every community-scripts
# install/ file uses.
source /dev/stdin <<<"$FUNCTIONS_FILE_PATH"
color
verb_ip6
catch_errors
setting_up_container
network_check
update_os

# Where the nano-proxmox config bundle (compose + clickhouse/vector/nginx) is
# pulled from. Override REPO_BRANCH=<branch> to test an unmerged branch.
REPO_OWNER="${REPO_OWNER:-nano-rs}"
REPO_BRANCH="${REPO_BRANCH:-main}"
DEPLOY_DIR="/opt/nano"

msg_info "Installing Dependencies"
$STD apt-get install -y \
  curl \
  ca-certificates \
  gnupg \
  openssl
msg_ok "Installed Dependencies"

msg_info "Installing Docker"
DOCKER_CONFIG_PATH='/etc/docker/daemon.json'
mkdir -p "$(dirname "$DOCKER_CONFIG_PATH")"
# journald log driver keeps the LXC disk from filling with json-file logs.
echo -e '{\n  "log-driver": "journald"\n}' >"$DOCKER_CONFIG_PATH"
$STD sh <(curl -fsSL https://get.docker.com)
msg_ok "Installed Docker"

msg_info "Fetching nano configuration"
mkdir -p "$DEPLOY_DIR"
# Extract install/files/* from the repo tarball straight into the deploy dir:
# docker-compose.yml, clickhouse/{config.d,users.d}, config/{vector,nginx}.
curl -fsSL "https://github.com/${REPO_OWNER}/nano-proxmox/archive/refs/heads/${REPO_BRANCH}.tar.gz" |
  tar -xz -C "$DEPLOY_DIR" --strip-components=3 "nano-proxmox-${REPO_BRANCH}/install/files"
# Mountpoint for the nano-vector-dynamic volume. The vector container binds
# config/vector at /etc/vector READ-ONLY, so Docker can't create the dynamic
# subdir itself; the api delivers parser configs here (NAN-1218).
mkdir -p "${DEPLOY_DIR}/config/vector/dynamic"
msg_ok "Fetched nano configuration"

msg_info "Generating secrets and environment"
# Generated once here and persisted to ${DEPLOY_DIR}/.env on the container disk,
# so a stack restart reuses the SAME keys. Rotating them would orphan
# secret-at-rest data (NANOSIEM_ENCRYPTION_KEY) and log everyone out (JWT_SECRET).
JWT_SECRET="$(openssl rand -hex 32)"
ENCRYPTION_KEY="$(openssl rand -hex 32)"
POSTGRES_PASSWORD="$(openssl rand -hex 16)"
CLICKHOUSE_PASSWORD="$(openssl rand -hex 16)"
CLICKHOUSE_ADMIN_PASSWORD="$(openssl rand -hex 16)"
VECTOR_AUTH_TOKEN="$(openssl rand -hex 24)"
# Container's primary IPv4 — drives CORS + auth-cookie scope (analysts hit nginx
# on :80 at this address).
LOCAL_IP="$(hostname -I | awk '{print $1}')"

cat <<EOF >"${DEPLOY_DIR}/.env"
# nano SIEM environment — generated by nano-proxmox install on first boot.
# Consumed by docker-compose.yml (\${...} interpolation). Keep this file.

# Public URL analysts hit (nginx reverse proxy). Drives CORS + cookie scope.
BASE_URL=http://${LOCAL_IP}

# Plain-HTTP appliance → dev mode so the auth refresh cookie is set without the
# Secure flag (browsers drop Secure cookies over http://). Front with HTTPS and
# set this to false for production exposure.
NANOSIEM_DEV_MODE=true

# --- Images ---
NANOSIEM_REGISTRY=ghcr.io/nano-rs
NANOSIEM_VERSION=latest

# --- Database ---
POSTGRES_USER=nanosiem
POSTGRES_DB=nanosiem
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
CLICKHOUSE_ADMIN_PASSWORD=${CLICKHOUSE_ADMIN_PASSWORD}

# --- Secrets ---
JWT_SECRET=${JWT_SECRET}
NANOSIEM_ENCRYPTION_KEY=${ENCRYPTION_KEY}

# --- Log ingestion ---
# Clients ship logs with: Authorization: Bearer \${VECTOR_AUTH_TOKEN}
VECTOR_AUTH_TOKEN=${VECTOR_AUTH_TOKEN}

# --- Published ports (host side) ---
HTTP_PORT=80
VECTOR_HTTP_PORT=8080
VECTOR_HEC_PORT=8088

# --- Retention / tier ---
HOT_RETENTION_DAYS=90
WARM_RETENTION_DAYS=30
NANO_TIER=unrestricted

RUST_LOG=info
EOF
chmod 600 "${DEPLOY_DIR}/.env"
msg_ok "Generated secrets and environment"

msg_info "Pulling nano images (first run downloads ~12 images — be patient)"
cd "$DEPLOY_DIR" || exit 1
# Serialize the pull: a fully-parallel pull fires dozens of simultaneous CDN
# lookups and can overwhelm a small resolver; retry to ride out hiccups
# (NAN-1224 / NAN-1230).
export COMPOSE_PARALLEL_LIMIT=1
pull_ok=0
for _ in 1 2 3 4 5; do
  if $STD docker compose pull; then
    pull_ok=1
    break
  fi
  sleep 15
done
if [[ "$pull_ok" -ne 1 ]]; then
  msg_error "Failed to pull images after 5 attempts (check network/DNS)"
  exit 1
fi
msg_ok "Pulled images"

msg_info "Starting nano SIEM stack"
$STD docker compose up -d --remove-orphans
msg_ok "Started nano SIEM stack"

msg_info "Waiting for nano API (first boot runs ClickHouse migrations)"
health_ok=0
for _ in $(seq 1 60); do
  if curl -fsS "http://127.0.0.1:80/api/health" >/dev/null 2>&1; then
    health_ok=1
    break
  fi
  sleep 5
done
if [[ "$health_ok" -eq 1 ]]; then
  msg_ok "nano API is healthy"
else
  msg_error "nano API did not become healthy within 5 minutes — check 'docker compose logs' in ${DEPLOY_DIR}"
fi

# Surface the ingest token (also in ${DEPLOY_DIR}/.env) for log-shipper setup.
{
  echo "nano SIEM ingest token (Authorization: Bearer <token>):"
  echo "  ${VECTOR_AUTH_TOKEN}"
} >~/nano.creds

motd_ssh
customize

msg_info "Cleaning up"
$STD apt-get -y autoremove
$STD apt-get -y autoclean
msg_ok "Cleaned"
